apiVersion: v1
kind: Service
metadata:
  name: node-port-service-with-ignore
  namespace: foospace
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
