name: helm-kube-score-test-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

      jobs:
        test-action-helm-job-linux:
          runs-on: ubuntu-latest
          name: kube-score Helm (Linux)
          steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: azure/setup-helm@v3
              name: Setup Helm
              with:
            - name: Make temporal output directory
              run: mkdir -p out/helm
            - name: Helm Template to standard template
              run: helm template ./hello-world > ./out/helm/sample-helm.yaml
            - name: kube-score action step
              uses: ./ # Uses an action in the root directory
              id: ksga
              with:
                manifests-folders: './out/helm/*.yaml'
                ignore-exit-code: 'true'
                kube-score-version: '1.14.0'