name: helm_validator

on: [push, workflow_dispatch, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0


      - name: Run kube-score
        run: |
            cd hello-world
            helm template hello-world | docker run -i zegl/kube-score:latest score \
              --ignore-test=pod-networkpolicy \
              --ignore-test=deployment-has-poddisruptionbudget 