name: helm_kube_score

on:
    push:
        paths:
            hello-world/

jobs:
  kube-score:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Run kube-score
          run: |
            wget https://github.com/zegl/kube-score/releases/download/v1.11.0/kube-score_1.11.0_linux_amd64
            chmod 755 kube-score_1.11.0_linux_amd64
            ls
            l