name: helm_kube_score

on: [push, workflow_dispatch, pull_request]

jobs:
  kube-score:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Run kube-score
          run: |
              wget https://github.com/zegl/kube-score/releases/download/v1.10.1/kube-score_1.10.1_linux_amd64 && \
                mv kube-score /usr/local/bin &&\
                kube-score