name: Validate charts

on:
    push:
      branches:
        - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run kube-score
        run: |
          for chart in manifests/*
          do
            echo ">>> Validating $chart"
                kube-score score $chart | docker run -i zegl/kube-score:latest score
            -
          done