name: kube_score_test_2

on: [push, workflow_dispatch]

jobs:
  kube-score:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Run kube-score
          run: |
              wget -q -O ./kube-score https://github.com/zegl/kube-score/releases/download/v1.10.1/kube-score_1.10.1_linux_amd64 && \
                chmod +x ./kube-score && \
                ./kube-score score manifests/*.yaml